### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mrichards42** [mrichards42/remarkable_puzzles#13]
**Absolutely before initial release**
- [x] clean up top menu bar (expand "?" to "help", nicer undo/redo buttons, maybe shrink "all games" button to gain space, etc.)
   - [x] use actual icons instead of text placeholders (undo, redo, back)
- [ ] draft config and icon
- [ ] official name -- is this "puzzles", or "st-puzzles", or "puzzle-collection"?

**Maybe before initial release**
- [x] header on chooser screen / about dialog, etc. There will ultimately be 2 or 3 screens of puzzles, so there should be some kind of page number indicator, so I don't think I can fit 5 rows of puzzles anyways.

**Some day**
- [ ] [custom params](https://www.chiark.greenend.org.uk/~sgtatham/puzzles/devel/midend.html#midend-get-config) dialog
- [x] A "swap short and long press" button, like PocketPuzzles and the Android port (i.e. [this icon](https://raw.githubusercontent.com/SteffenBauer/PocketPuzzles/master/icons/controls/bt_swap.bmp))

**Comment by Eeems** [comment]
@mrichards42 do you have plans to add an application icon still?

**Comment by mrichards42** [comment]
Hey @Eeems I don't have plans to work on this repo in the near future since I'm not using it, but I'm happy to review and merge a PR if you or anyone else wants to make an app icon. Also happy to turn this over to the community if someone is excited about picking up maintenance.

**Comment by raisjn** [comment]
@mrichards42: thanks for the cool app and all the features along the way, I learned a bunch from you! 

would be happy to adopt puzzles into rmkit-dev, I think you may be in the org already

**Comment by mrichards42** [comment]
Hey @raisjn thanks for the offer, I can transfer to the rmkit-dev org soon. I'm already part of it :) I had a great time working with you on stuff a few years ago, and I learned a ton too! Things have just gotten a lot busier since the pandemic ended, but hopefully this will get a little more life.

**Comment by mrichards42** [comment]
@raisjn I think you forked this repo into rmkit-dev. If you can delete that one I'll transfer this repo over!

**Comment by raisjn** [comment]
> @raisjn I think you forked this repo into rmkit-dev. If you can delete that one I'll transfer this repo over!

done!
